version: '3.8'

services:

  web:
    container_name: web
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
      - ./app/web:/var/www/html

  app:
    container_name: app
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./docker/app/default.conf:/etc/nginx/conf.d/default.conf
      - ./app/app:/var/www/html

